#ifndef _HOME_DT_PROJECTS_WEBTEST_DAY13_SRC_INCLUDE_UTIL_H_
#define _HOME_DT_PROJECTS_WEBTEST_DAY13_SRC_INCLUDE_UTIL_H_
void Errif(bool condition, const char *errmsg);
#endif  // _HOME_DT_PROJECTS_WEBTEST_DAY13_SRC_INCLUDE_UTIL_H_"
